-- Migration 034: retired drift-overrule layer.
--
-- This migration used to add post-prediction drift override columns. DRIFT_PROBE
-- is now a normal production strategy, so the override layer is intentionally
-- not created in fresh schemas. Migration 036 drops the legacy columns from
-- existing databases.
